---
- name: GitHub Runner | Configure the runner
  ansible.builtin.command:
    chdir: /opt/actions-runner-linux-x64-{{ github_runner_version }}
    argv:
      - su
      - -c
      - ./config.sh {{ parameters | join(' ') }}
      - "{{ github_runner_user }}"
    creates: /opt/actions-runner-linux-x64-{{ github_runner_version }}/.credentials
  vars:
    parameters:
      - --url {{ github_runner_config.url }}
      - --token {{ github_runner_config.token }}
      - --name {{ ansible_facts["nodename"] }}
      - --work _work
      - --labels '{{ github_runner_config.labels | join(",") }}'
      - --runnergroup '{{ github_runner_config.pool | default("Default") }}'
  no_log: true

- name: GitHub Runner | Copy service exectuable
  ansible.builtin.copy:
    dest: /opt/actions-runner-linux-x64-{{ github_runner_version }}
    group: "{{ github_runner_group }}"
    mode: '0755'
    owner: "{{ github_runner_user }}"
    remote_src: true
    src: /opt/actions-runner-linux-x64-{{ github_runner_version }}/bin/runsvc.sh

- name: GitHub Runner | Add gtihub-runner service configuration
  ansible.builtin.template:
    dest: /etc/systemd/system/github-runner.service
    owner: root
    group: root
    mode: '0664'
    src: github-runner.service.j2
  notify: Restart Github Runner
  register: systemd_unit

- name: GitHub Runner | Reload systemd configurations
  ansible.builtin.systemd:
    daemon_reload: true

- name: GitHub Runner | Start github-runner service
  ansible.builtin.service:
    enabled: true
    name: github-runner
    state: started
