---
- name: GitHub Runner | Install packages
  ansible.builtin.apt:
    install_recommends: false
    name: tar

- name: GitHub Runner | Create runner group
  ansible.builtin.group:
    name: "{{ github_runner_group }}"

- name: GitHub Runner | Create runner user
  ansible.builtin.user:
    create_home: false
    group: "{{ github_runner_group }}"
    home: /opt/actions-runner-linux-x64-{{ github_runner_version }}
    name: "{{ github_runner_user }}"
    shell: /bin/sh
    system: true

- name: GitHub Runner | Check if GitHub Runner directory is available
  ansible.builtin.stat:
    path: /opt/actions-runner-linux-x64-{{ github_runner_version }}
  register: github_runner_dir

- name: GitHub Runner | Add executables directory
  ansible.builtin.file:
    group: "{{ github_runner_group }}"
    mode: 0775
    owner: "{{ github_runner_user }}"
    path: /opt/actions-runner-linux-x64-{{ github_runner_version }}
    state: directory
  when: not github_runner_dir.stat.exists

- name: GitHub Runner | Check if GitHub Runner executables are available
  ansible.builtin.stat:
    path: /opt/actions-runner-linux-x64-{{ github_runner_version }}/bin
  register: github_runner_executables

- name: GitHub Runner | Download GitHub Runner executables
  ansible.builtin.unarchive:
    dest: /opt/actions-runner-linux-x64-{{ github_runner_version }}
    group: "{{ github_runner_group }}"
    owner: "{{ github_runner_user }}"
    remote_src: true
    src: https://github.com/actions/runner/releases/download/v{{ github_runner_version }}/actions-runner-linux-x64-{{ github_runner_version }}.tar.gz
  when: not github_runner_executables.stat.exists

- name: GitHub Runner | Install dependencies
  ansible.builtin.shell:
    chdir: /opt/actions-runner-linux-x64-{{ github_runner_version }}
    cmd: DEBIAN_FRONTEND=noninteractive ./bin/installdependencies.sh
  when: not github_runner_executables.stat.exists
